services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "6542:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  stats-server:
    build:
      context: .
      dockerfile: ewm-stats-service/ewm-stats-server/Dockerfile
      args:
        JAR_FILE: ewm-stats-service/ewm-stats-server/target/ewm-stats-server-0.0.1-SNAPSHOT.jar
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      stats-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ewm-network

#Заглушка основого сервиса
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "6543:5432"
    volumes:
      - ewm_data:/var/lib/postgresql/data
    networks:
      - ewm-network

volumes:
  stats_data:
  ewm_data:

networks:
  ewm-network:
    driver: bridge